# Generated by Django 6.0.1 on 2026-02-04 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_passwordresetotp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='company_name',
        ),
    ]
