# Generated by Django 6.0.1 on 2026-02-04 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_remove_employee_company_name'),
        ('jobseeker', '0016_job_salary_max_job_salary_min'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='jobseeker.company'),
            preserve_default=False,
        ),
    ]
