# Generated by Django 6.0.1 on 2026-02-17 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_interview'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('hr', 'HR'), ('recruiter', 'Recruiter')], default='recruiter', max_length=20),
        ),
    ]
