# Generated by Django 6.0.1 on 2026-04-13 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_employee_is_active_employee_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='reminder_sent_1hr',
            field=models.BooleanField(default=False),
        ),
    ]
