# Generated by Django 6.0.1 on 2026-02-18 04:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_conversation_jobseeker'),
        ('jobseeker', '0029_jobseeker_phone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='conversation',
            unique_together={('job', 'jobseeker')},
        ),
    ]
