# Generated by Django 6.0.1 on 2026-01-24 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0003_userappliedjob_usersavedjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker',
            name='token_version',
            field=models.IntegerField(default=1),
        ),
    ]
