# Generated by Django 6.0.1 on 2026-01-27 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0005_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobseeker',
            name='token_version',
        ),
    ]
