# Generated by Django 6.0.1 on 2026-01-27 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0006_remove_jobseeker_token_version'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Job',
        ),
    ]
