# Generated by Django 6.0.1 on 2026-02-02 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0012_landingchoice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LandingChoice',
        ),
    ]
