# Generated by Django 6.0.1 on 2026-02-03 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0013_delete_landingchoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
