# Generated by Django 6.0.1 on 2026-02-04 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0014_jobseeker_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='salary',
        ),
    ]
