# Generated by Django 6.0.1 on 2026-02-04 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0015_remove_job_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='salary_max',
            field=models.IntegerField(blank=True, help_text='Maximum salary in LPA', null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='salary_min',
            field=models.IntegerField(blank=True, help_text='Minimum salary in LPA', null=True),
        ),
    ]
