# Generated by Django 6.0.1 on 2026-02-05 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0016_job_salary_max_job_salary_min'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobseeker',
            name='experience',
        ),
        migrations.AddField(
            model_name='jobseeker',
            name='total_experience',
            field=models.PositiveIntegerField(default=0, help_text='Total experience in years'),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='title',
            field=models.CharField(blank=True, help_text='Desired job role (e.g. Backend Developer)', max_length=200),
        ),
        migrations.CreateModel(
            name='JobExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, help_text='Leave empty if currently working', null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('jobseeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='jobseeker.jobseeker')),
            ],
        ),
    ]
