# Generated by Django 6.0.1 on 2026-02-05 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0019_jobalert_last_read_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='posted_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
