# Generated by Django 6.0.1 on 2026-02-11 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0024_skill_jobseeker_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobseeker',
            name='total_experience',
        ),
    ]
