# Generated by Django 6.0.1 on 2026-02-17 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0027_alter_company_options_company_is_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
