# Generated by Django 6.0.1 on 2026-02-17 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0028_alter_company_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
