# Generated by Django 6.0.1 on 2026-02-19 04:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0029_jobseeker_phone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userappliedjob',
            name='status',
            field=models.CharField(choices=[('APPLIED', 'Applied'), ('UNDER_REVIEW', 'Under Review'), ('SHORTLISTED', 'Shortlisted'), ('REJECTED', 'Rejected'), ('SELECTED', 'Selected')], default='APPLIED', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='userappliedjob',
            unique_together={('user', 'job')},
        ),
    ]
