# Generated by Django 6.0.1 on 2026-02-19 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0030_userappliedjob_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userappliedjob',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
    ]
