# Generated by Django 6.0.1 on 2026-02-20 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0031_userappliedjob_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userappliedjob',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobseeker.job'),
        ),
    ]
