# Generated by Django 6.0.1 on 2026-02-23 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0035_jobseekerpreference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='location',
        ),
    ]
