# Generated by Django 6.0.1 on 2026-02-24 04:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0036_remove_job_location'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobseekerPrivacySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_visibility', models.CharField(choices=[('public', 'Public'), ('recruiters_only', 'Recruiters Only'), ('private', 'Private')], default='recruiters_only', max_length=20)),
                ('show_email', models.BooleanField(default=False, help_text='NOTE :if you turn off employer not able to contact you')),
                ('show_phone', models.BooleanField(default=False, help_text='NOTE :if you turn off employer not able to contact you')),
                ('show_resume', models.BooleanField(default=True, help_text='NOTE :if you turn off employer not able to contact you')),
                ('is_searchable', models.BooleanField(default=True)),
                ('allow_anonymous_applications', models.BooleanField(default=False)),
                ('allow_recruiter_messages', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='privacy_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
