# Generated by Django 6.0.1 on 2026-02-24 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0037_jobseekerprivacysettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersavedjob',
            name='is_anonymous',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='jobseekerprivacysettings',
            name='allow_recruiter_messages',
            field=models.BooleanField(default=True, help_text='NOTE :if you turn off employer not able to search you'),
        ),
        migrations.AlterField(
            model_name='jobseekerprivacysettings',
            name='is_searchable',
            field=models.BooleanField(default=True, help_text='NOTE :if you turn off employer not able to search you'),
        ),
    ]
