# Generated by Django 6.0.1 on 2026-02-25 04:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0038_usersavedjob_is_anonymous_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseekerprivacysettings',
            name='allow_recruiter_messages',
            field=models.BooleanField(default=True, help_text='NOTE :if you turn off employer not able to message you'),
        ),
        migrations.CreateModel(
            name='JobseekerActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('APPLIED_JOB', 'Applied Job'), ('SAVED_JOB', 'Saved Job'), ('VIEWED_JOB', 'Viewed Job'), ('UPDATED_PROFILE', 'Updated Profile'), ('UPLOADED_RESUME', 'Uploaded Resume'), ('UPDATED_PREFERENCE', 'Updated Preference'), ('UPDATED_PRIVACY', 'Updated Privacy Settings')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
