# Generated by Django 6.0.1 on 2026-02-26 03:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0039_alter_jobseekerprivacysettings_allow_recruiter_messages_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseekeractivitylog',
            name='action_type',
            field=models.CharField(choices=[('APPLIED_JOB', 'Applied Job'), ('SAVED_JOB', 'Saved Job'), ('VIEWED_JOB', 'Viewed Job'), ('UPDATED_PROFILE', 'Updated Profile'), ('UPLOADED_RESUME', 'Uploaded Resume'), ('UPDATED_PREFERENCE', 'Updated Preference'), ('UPDATED_PRIVACY', 'Updated Privacy Settings'), ('UPDATED_AVATAR', 'updated profile picture'), ('REMOVED_AVATAR', 'removed profile picture'), ('UPDATED_PASSWORD', 'password changed')], max_length=50),
        ),
        migrations.CreateModel(
            name='JobRecommendationFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(choices=[('LIKE', 'Like'), ('DISLIKE', 'Dislike'), ('NOT_RELEVANT', 'Not Relevant'), ('HIDE', 'Hide')], max_length=30)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_feedbacks', to='jobseeker.job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'job')},
            },
        ),
    ]
