# Generated by Django 6.0.1 on 2026-02-26 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0040_alter_jobseekeractivitylog_action_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrecommendationfeedback',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
