# Generated by Django 6.0.1 on 2026-03-09 00:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobseeker", "0041_jobrecommendationfeedback_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=5,
                max_digits=8,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(-90),
                    django.core.validators.MaxValueValidator(90),
                ],
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=5,
                max_digits=9,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(-180),
                    django.core.validators.MaxValueValidator(180),
                ],
            ),
        ),
    ]
