# Generated by Django 6.0.1 on 2026-03-16 06:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0045_alter_jobseeker_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='resumetoggle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ispubilc', models.BooleanField(default=True, help_text='it allows all user of this app can accesss your resume')),
                ('Isrecruiters_only', models.BooleanField(default=False, help_text='it allow only verified recruiters to access your resume')),
                ('Isprivate', models.BooleanField(default=False, help_text='no one allow to view your resume untill you aplly the job with resume')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_toggle', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
