# Generated by Django 6.0.1 on 2026-03-16 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0046_resumetoggle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resumetoggle',
            old_name='Isprivate',
            new_name='isprivate',
        ),
        migrations.RenameField(
            model_name='resumetoggle',
            old_name='Ispubilc',
            new_name='ispubilc',
        ),
        migrations.RenameField(
            model_name='resumetoggle',
            old_name='Isrecruiters_only',
            new_name='isrecruiters_only',
        ),
    ]
