# Generated by Django 6.0.1 on 2026-03-16 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0047_rename_isprivate_resumetoggle_isprivate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resumetoggle',
            old_name='isprivate',
            new_name='is_private',
        ),
        migrations.RenameField(
            model_name='resumetoggle',
            old_name='ispubilc',
            new_name='is_public',
        ),
        migrations.RenameField(
            model_name='resumetoggle',
            old_name='isrecruiters_only',
            new_name='is_recruiters_only',
        ),
    ]
