# Generated by Django 6.0.1 on 2026-03-18 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0049_versioncontrol'),
    ]

    operations = [
        migrations.AddField(
            model_name='versioncontrol',
            name='version',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
