# Generated by Django 6.0.1 on 2026-03-23 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0050_versioncontrol_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobseekercertificates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate', models.FileField(blank=True, null=True, upload_to='certificate/')),
                ('certificatetype', models.FileField(blank=True, choices=[('10TH', '10th Certificate'), ('12TH', '12th Certificate'), ('DIPLOMA', 'Diploma'), ('UG', 'Undergraduate'), ('PG', 'Postgraduate'), ('SKILL', 'Skill Certificate'), ('INTERNSHIP', 'Internship Certificate'), ('PROJECT', 'Project Certificate'), ('OTHER', 'Other')], null=True, upload_to='')),
                ('othertype', models.CharField(blank=True, help_text='please make space', max_length=300)),
                ('jobseeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='jobseeker.jobseeker')),
            ],
        ),
    ]
