# Generated by Django 6.0.1 on 2026-03-23 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0051_jobseekercertificates'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobseekercertificates',
            old_name='othertype',
            new_name='custom_name',
        ),
        migrations.AddField(
            model_name='jobseekercertificates',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='jobseekercertificates',
            name='certificatetype',
            field=models.CharField(blank=True, choices=[('10TH', '10th Certificate'), ('12TH', '12th Certificate'), ('DIPLOMA', 'Diploma'), ('UG', 'Undergraduate'), ('PG', 'Postgraduate'), ('SKILL', 'Skill Certificate'), ('INTERNSHIP', 'Internship Certificate'), ('PROJECT', 'Project Certificate'), ('OTHER', 'Other')], null=True),
        ),
    ]
