# Generated by Django 6.0.1 on 2026-03-23 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0052_rename_othertype_jobseekercertificates_custom_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekercertificates',
            name='document_name',
            field=models.CharField(blank=True, choices=[('MARKSHEET', 'Marksheet'), ('CONSOLIDATED', 'Consolidated Marksheet'), ('PROVISIONAL', 'Provisional Certificate'), ('TRANSFER_CERTIFICATE', 'Transfer Certificate (TC)'), ('BONAFIDE', 'Bonafide Certificate'), ('DEGREE', 'Degree Certificate'), ('DIPLOMA_CERT', 'Diploma Certificate'), ('COURSE_COMPLETION', 'Course Completion Certificate'), ('EXPERIENCE_LETTER', 'Experience Letter'), ('INTERNSHIP_CERT', 'Internship Certificate'), ('PROJECT_CERT', 'Project Certificate'), ('OTHER', 'Other')], null=True),
        ),
        migrations.AlterField(
            model_name='jobseekercertificates',
            name='certificatetype',
            field=models.CharField(blank=True, choices=[('10TH', '10th Certificate'), ('12TH', '12th Certificate'), ('DIPLOMA', 'Diploma'), ('UG', 'Undergraduate'), ('PG', 'Postgraduate'), ('SKILL', 'Skill Certificate'), ('INTERNSHIP', 'Internship Certificate'), ('EXPERIENCE', 'Experience Certificate'), ('PROJECT', 'Project Certificate'), ('OTHER', 'Other')], null=True),
        ),
    ]
