# Generated by Django 6.0.1 on 2026-03-23 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0053_jobseekercertificates_document_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobseekercertificates',
            old_name='custom_name',
            new_name='custom_certificate_name',
        ),
        migrations.AddField(
            model_name='jobseekercertificates',
            name='custom_document_name',
            field=models.CharField(blank=True, help_text='please make space', max_length=300),
        ),
    ]
