# Generated by Django 6.0.1 on 2026-03-23 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0054_rename_custom_name_jobseekercertificates_custom_certificate_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobseekercertificates',
            name='custom_document_name',
        ),
    ]
