# Generated by Django 6.0.1 on 2026-03-23 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0055_remove_jobseekercertificates_custom_document_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobseekercertificates',
            old_name='document_name',
            new_name='custom_document_name',
        ),
    ]
