# Generated by Django 6.0.1 on 2026-03-23 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0056_rename_document_name_jobseekercertificates_custom_document_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekercertificates',
            name='document_name',
            field=models.CharField(blank=True, choices=[('MARKSHEET', 'Marksheet'), ('CONSOLIDATED', 'Consolidated Marksheet'), ('PROVISIONAL', 'Provisional Certificate'), ('TRANSFER_CERTIFICATE', 'Transfer Certificate (TC)'), ('BONAFIDE', 'Bonafide Certificate'), ('DEGREE', 'Degree Certificate'), ('DIPLOMA_CERT', 'Diploma Certificate'), ('COURSE_COMPLETION', 'Course Completion Certificate'), ('EXPERIENCE_LETTER', 'Experience Letter'), ('INTERNSHIP_CERT', 'Internship Certificate'), ('PROJECT_CERT', 'Project Certificate'), ('OTHER', 'Other')], null=True),
        ),
        migrations.AlterField(
            model_name='jobseekercertificates',
            name='custom_document_name',
            field=models.CharField(blank=True, help_text='please make space', max_length=300),
        ),
    ]
