# Generated by Django 6.0.1 on 2026-03-25 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0057_jobseekercertificates_document_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobseeker',
            name='education',
        ),
        migrations.CreateModel(
            name='Jobseekereducationdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education_type', models.CharField(blank=True, choices=[('10TH', '10th School'), ('12TH', '12th School'), ('DIPLOMA', 'Diploma_institute'), ('UG', 'Undergraduate_institute'), ('PG', 'Postgraduate_institute')], null=True)),
                ('school_name', models.CharField(blank=True, null=True)),
                ('college_name', models.CharField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('jobseeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_details', to='jobseeker.jobseeker')),
            ],
        ),
    ]
