# Generated by Django 6.0.1 on 2026-03-25 06:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0058_remove_jobseeker_education_jobseekereducationdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekereducationdetails',
            name='percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
