# Generated by Django 6.0.1 on 2026-03-25 06:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0059_jobseekereducationdetails_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekereducationdetails',
            name='history_of_backlog',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobseekereducationdetails',
            name='studying',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='jobseekereducationdetails',
            name='percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
