# Generated by Django 6.0.1 on 2026-04-01 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0060_jobseekereducationdetails_history_of_backlog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobexperience',
            name='uuid',
            field=models.UUIDField(null=True),
        ),
        migrations.AlterField(
            model_name='jobseekereducationdetails',
            name='education_type',
            field=models.CharField(blank=True, choices=[('10TH', '10th '), ('12TH', '12th '), ('DIPLOMA', 'Diploma'), ('UG', 'Undergraduate'), ('PG', 'Postgraduate')], null=True),
        ),
    ]
