# Generated by Django 6.0.1 on 2026-04-01 04:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0061_jobexperience_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobexperience',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True, unique=True),
        ),
    ]
