# Generated by Django 6.0.1 on 2026-04-06 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0062_alter_jobexperience_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobseeker',
            name='skills',
        ),
    ]
