# Generated by Django 6.0.1 on 2026-04-06 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0063_remove_jobseeker_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobseekerskills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobseeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobseeker_skills', to='jobseeker.jobseeker')),
                ('skills', models.ManyToManyField(related_name='skills', to='jobseeker.skill')),
            ],
        ),
    ]
