# Generated by Django 6.0.1 on 2026-04-06 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0064_jobseekerskills'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekerskills',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
