# Generated by Django 6.0.1 on 2026-04-06 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0065_jobseekerskills_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekerskills',
            name='custom_skills',
            field=models.CharField(blank=True, help_text='Comma separated skills & if the skills not in list type on your own '),
        ),
    ]
