# Generated by Django 6.0.1 on 2026-04-06 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0066_jobseekerskills_custom_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='skills', to='jobseeker.skill'),
        ),
        migrations.DeleteModel(
            name='Jobseekerskills',
        ),
    ]
