# Generated by Django 6.0.1 on 2026-04-06 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0067_jobseeker_skills_delete_jobseekerskills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobseeker',
            name='skills',
        ),
        migrations.CreateModel(
            name='Jobseekerskills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_skills', models.TextField(blank=True, help_text='Comma separated skills entered by user')),
                ('jobseeker', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='jobseeker.jobseeker')),
                ('skills', models.ManyToManyField(blank=True, related_name='jobseekers', to='jobseeker.skill')),
            ],
        ),
    ]
