# Generated by Django 6.0.1 on 2026-04-13 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0069_pendingskill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseekercertificates',
            name='document_name',
            field=models.CharField(blank=True, choices=[('MARKSHEET', 'Marksheet'), ('CONSOLIDATED', 'Consolidated Marksheet'), ('PROVISIONAL', 'Provisional Certificate'), ('TRANSFER_CERTIFICATE', 'Transfer Certificate (TC)'), ('BONAFIDE', 'Bonafide Certificate'), ('DEGREE', 'Degree Certificate'), ('DIPLOMA_CERT', 'Diploma Certificate'), ('COURSE_COMPLETION', 'Course Completion Certificate'), ('EXPERIENCE_LETTER', 'Experience Letter'), ('PROJECT_CERT', 'Project Certificate'), ('OTHER', 'Other')], null=True),
        ),
        migrations.AlterField(
            model_name='jobseekerskills',
            name='custom_skills',
            field=models.TextField(blank=True, help_text='Comma separated skills entered by user', max_length=100, unique=True),
        ),
    ]
