# Generated by Django 6.0.1 on 2026-04-16 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0070_alter_jobseekercertificates_document_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobalert',
            name='last_notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
