from django.urls import path
from .views import (JobSeekerAvatarAPI, JobSeekerRegistrationAPI , JobSeekerProfileAPI , 
                    ChangePasswordAPI, JobSeekerDashboardCountAPI ,LogoutAPI,CompanyJobsAPI , 
                    CompanyLogoUploadAPI , JobSeekerOpportunitiesCompanyListAPI ,  JobSeekerOpportunitiesOverviewAPI,
                     LandingJobListingAPI,ApplyJobAPIView , JobAlertCreateAPIView , JobAlertListAPIView, 
                     JobAlertDetailAPIView, JobAlertMatchesAPIView,
                     JobAlertNewCountAPIView,JobCategoryListAPIView, 
                     JobCategoryAPI , ResumeUploadAPIView ,ProfileCompletionAPIView, SkillAssessmentAPIView,
                      JobseekerApplicationStatusAPIView , AIChatbotAPIView ,
                       RecommendedJobsAPIView, JobseekerInterviewListAPIView, 
                       JobseekerActivityLogAPIView,JobViewTrackAPIView , JobseekerPreferenceView, 
                       JobseekerDashboardSummaryAPIView,JobseekerPrivacySettingsAPIView , 
                       JobRecommendationFeedbackAPIView , AdvancedProfileStrengthAPIView , WeeklyJobMatchAPIView, ApplicationAnalyticsAPIView,
                       NearbyJobsAPIView,
                       JobseekerPerformanceInsightsAPIView, NearbyJobsFromProfileAPIView,  SimilarJobsAPIView,
                       ProjectPortfolioListApiView,ProjectPortfolioListApiViewSpecific, ResumeToggleApiView, 
                       ResumeversionlistApi, JobSeekerDocumentReceivedApi,JobSeekerDocumentReceivedRUDApiView, 
                       JobSeekerEducationDetailsApi,JobSeekerEducationDetailsRUDApiView, JobSeekerExperienceDetailsApi,JobSeekerExperienceRUDApiView)
urlpatterns = [
    path('avatar/', JobSeekerAvatarAPI.as_view(), name='jobseeker-avatar'),
    path('register/', JobSeekerRegistrationAPI.as_view(), name='jobseeker-register'),
    path("profile/", JobSeekerProfileAPI.as_view(), name="jobseeker-profile"),
    path("api/change-password/", ChangePasswordAPI.as_view(), name="change-password"),
    path("dashboard/counts/",JobSeekerDashboardCountAPI.as_view(),name="jobseeker-dashboard-counts"),
    path("api/logout/", LogoutAPI.as_view(), name="logout"),
    path("company/<int:company_id>/jobs/",CompanyJobsAPI.as_view(),name="company-jobs",),
    path("companies/<int:company_id>/upload-logo/",CompanyLogoUploadAPI.as_view(),name="company-logo-upload"),
    path("jobseeker/opportunities/companies/",JobSeekerOpportunitiesCompanyListAPI.as_view(),name="jobseeker-opportunities-companies"),
    path("opportunities/overview/",JobSeekerOpportunitiesOverviewAPI.as_view(),name="jobseeker-opportunities-overview"),
    path("jobs/<int:job_id>/view/",JobViewTrackAPIView.as_view(),name="jobseeker-individualjobview"),
    path("landing/jobs/", LandingJobListingAPI.as_view(),name="jobseeker-landing-joblisting"),
    path("jobs/apply/", ApplyJobAPIView.as_view(), name="apply-job"),
    path("job-alerts/create/",JobAlertCreateAPIView.as_view(),name="job-alert-create"),
    path("job-alerts/", JobAlertListAPIView.as_view(), name="job-alert-list"),
    path("job-alerts/<int:pk>/",JobAlertDetailAPIView.as_view(),name="job-alert-detail"),
    path("job-alerts/<int:alert_id>/matches/",JobAlertMatchesAPIView.as_view(),name="job-alert-matches"),
    path("job-alerts/<int:alert_id>/new-count/",JobAlertNewCountAPIView.as_view(),name="job-alert-new-count"),
    path( "job-categories/list/",JobCategoryListAPIView.as_view(), name="job-category-lists"), 
    path("job-categories/list/<int:category_id>/",JobCategoryAPI.as_view(),name="job-category-jobs"),
    path("profile/resume/",ResumeUploadAPIView.as_view(),name="resume-upload"),
    path("profile/projects/", ProjectPortfolioListApiView.as_view(), name="project-portfolio-list-create"),
    path("profile/projects/<int:pk>/", ProjectPortfolioListApiViewSpecific.as_view(), name="project-portfolio-detail"),
    path("profile/completion_details/",ProfileCompletionAPIView.as_view(),name="profile_completion_details"),
    path("profile/skill-assessment/", SkillAssessmentAPIView.as_view(),name="skills_assessment_score"),
    path("chatbot/help/", AIChatbotAPIView.as_view(),name="chat-bot"),
    path("interview/my/", JobseekerInterviewListAPIView.as_view(),name="interview_view"),
    path("applications/status/", JobseekerApplicationStatusAPIView.as_view(),name="application_view"),
    path("preferences/", JobseekerPreferenceView.as_view(), name="jobseeker-preferences"),
    path("preferences-jobs/", RecommendedJobsAPIView.as_view(),name="jobseeker-preferences-lists"),
    path("privacy-settings/",JobseekerPrivacySettingsAPIView.as_view(),name="jobseeker-privacy-settings",),
    path("activity-logs/",JobseekerActivityLogAPIView.as_view(),name="jobseeker-activity-logs"),
    path("recommendation-feedback/",JobRecommendationFeedbackAPIView.as_view(),name="recommendation-feedback",),
    path("dashboard/summary/",JobseekerDashboardSummaryAPIView.as_view(),name="jobseeker-dashboard-summary"),
    path("profile/advanced-strength/",AdvancedProfileStrengthAPIView.as_view(),name="advanced-profile-strength",),
    path("profile/weekly-market-intelligence/", WeeklyJobMatchAPIView.as_view(),name="weekly-market-intelligence",),
    path("applications/analytics/",ApplicationAnalyticsAPIView.as_view(),name="application-analytics"),
    path("performance/insights/", JobseekerPerformanceInsightsAPIView.as_view(), name="jobseeker-performance-insights"),
    path("jobs/nearby/", NearbyJobsAPIView.as_view(), name="nearby-jobs"),
    path("jobs/nearby/me/", NearbyJobsFromProfileAPIView.as_view(), name="nearby-jobs-me"),
    path("jobs/similar/<int:job_id>/",SimilarJobsAPIView.as_view(),name="similar-jobs"),
    path("resume-toggles/",ResumeToggleApiView.as_view(),name="toggle-resume"),
    path("resume/history/",ResumeversionlistApi.as_view(),name ="resume-history"),
    path("documents/upload/",JobSeekerDocumentReceivedApi.as_view(),name ="documents-uploaded"),
    path("documents/upload/<int:pk>/",JobSeekerDocumentReceivedRUDApiView.as_view(),name ="documents-uploaded-edit"),
    path("education-details/",JobSeekerEducationDetailsApi.as_view(),name ="education-details"),
    path("education-details/<int:pk>/",JobSeekerEducationDetailsRUDApiView.as_view(),name ="education-details-edit"),
    path("experience-details/",JobSeekerExperienceDetailsApi.as_view(),name ="experience-details"),
    path("experience-details/<int:pk>/",JobSeekerExperienceRUDApiView.as_view(),name ="experience-details"),
     ]


